### ISSUE TITLE
bundle install bug

### ISSUE THREAD

**Issue by ziomek-z-ulicy** [efxtv/Install-Metasploit-Framework-6-in-Termux#27]
~/metasploit-framework $ msfconsole                             Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.                        Could not find mini_portile2-2.8.4 in any of the sources        Run `bundle install` to install missing gems.
~/metasploit-framework $ bundle install
bash: /data/data/com.termux/files/usr/bin/bundle: cannot execute: required file not found
~/metasploit-framework $

**Comment by efxtv** [comment]
join t.me/efxtv for more
